name: Deployment-Workflow
 
on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Select the environment to deploy to'
          required: true
          default: 'TEST'
          type: choice
          options:
            - TEST
            - STG
            - PRD
        release_version:
          type: choice
          description: Select the release version
          required: true
          options:
            - v1.0.0
            - v1.0.1
            - v1.0.2
            - v1.0.3
            - v1.0.4
            - v1.0.5
            - v1.0.6 
            - v1.0.7 
            - v1.0.8 
            - v1.0.9 
            - v1.0.10 
        project_name:
          type: choice
          description: Select the project you wish to deploy
          default: ''
          required: true
          options:
            - WATER_DM
            - OPERATIONS_DM
            - SOURCE_DM
            - COMMON_DM
            - WQD_DM
            - ENERGY_DM
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up environment
      run: |
        echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
    - name: Get the latest release (if release_version is not specified)
      id: get_latest_release
      if: github.event.inputs.release_version == ''
      uses: actions/github-script@v4
      with:
        script: |
          const latestRelease = await github.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return latestRelease.data.tag_name;
    - name: Set release version to latest (if release_version is not specified)
      if: github.event.inputs.release_version == ''
      run: echo "RELEASE_VERSION=${{ steps.get_latest_release.outputs.result }}" >> $GITHUB_ENV
    - name: Set up environment variables
      run: | 
       echo "Setting up variables..."
       export VERSIONID=${{ env.RELEASE_VERSION }}
       echo "Deploy version is $VERSIONID"

    - name: Ensure permissions
      run: chmod -R u+rwx ${{ github.workspace }}

    - name: Remove anything
      if: always()  # This ensures that the step runs regardless of the outcome of previous steps
      run: |
        rm -rf ${{ github.workspace }}/*
    
    - name: Download and extract release asset
      uses: robinraju/release-downloader@v1
      with:
        repository: ${{ github.repository }}
        tag: ${{ env.RELEASE_VERSION }}
        fileName: 'ADW-${{ env.RELEASE_VERSION }}.zip'
        latest: false
        extract: true

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_PRIVATE_KEY }}" | base64 --decode > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
        echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
 
    - name: Set execute permissions
      run: chmod +x ./DevOps/plsql/main.sh

    - name: Remove line terminators
      run: sed -i 's/\r//g' ./DevOps/plsql/main.sh

    - name: Retrieve schema credentials from OCI Vault
      run: |
        case "${{ github.event.inputs.project_name }}" in
          WATER_DM)
            SECRET_ID="${{ secrets.WATER_DM_SECRET }}"
            ;;
          OPERATIONS_DM)
            SECRET_ID="${{ secrets.OPERATIONS_DM_SECRET }}"
            ;;
          SOURCE_DM)
            SECRET_ID="${{ secrets.SOURCE_DM_SECRET }}"
            ;;
          COMMON_DM)
            SECRET_ID="${{ secrets.COMMON_DM_SECRET }}"
            ;;
          WQD_DM)
            SECRET_ID="${{ secrets.WQD_DM_SECRET }}"
            ;;
          ENERGY_DM)
            SECRET_ID="${{ secrets.ENERGY_DM_SECRET }}"
            ;;
          *)
            echo "Unknown project name: ${{ github.event.inputs.project_name }}"
            exit 1
            ;;
        esac
        echo "Checking the valut pass here"
        DB_CREDENTIALS=$(oci secrets secret-bundle get --secret-id "$SECRET_ID" --query 'data."secret-bundle-content".content' --raw-output | base64 --decode)
        echo "db_credentials=$DB_CREDENTIALS" >> $GITHUB_ENV

    - name: Define variables and secrets
      env:
        WORKSPACE: ${{ vars.WORKSPACE }}
        SCRIPT_DIR: ${{ vars.SCRIPT_DIR }}
        CREDENTIAL_NAME: ${{ secrets.CREDENTIAL_NAME }}
        CURATED_BUCKET: ${{ vars.CURATED_BUCKET }}
        RAW_BUCKET: ${{ vars.RAW_BUCKET }}
        PRESENTATION_BUCKET: ${{vars.PRESENTATION_BUCKET}}
        NAMESPACE: ${{ secrets.NAMESPACE }}
        CURATED_PRE_AUTH: ${{ secrets.CURATED_PRE_AUTH }}
        RAW_PRE_AUTH: ${{ secrets.RAW_PRE_AUTH }}
        PRESENTATION_PRE_AUTH: ${{secrets.PRESENTATION_PRE_AUTH}}
        WNAME: ${{ secrets.WNAME }}
        ENV: ${{ secrets.ADW_ENV }}
        DB_USERNAME: ${{ github.event.inputs.project_name }}
        DB_PASSWORD: "${{ env.db_credentials }}"
        VERSIONID: ${{ env.VERSIONID }}
        PROJECT_NAME: ${{ github.event.inputs.project_name }}
        DEPLOY_VERSION: ${{ github.event.inputs.release_version }}
      run: |
        if find ./ADW/${VERSIONID}/${{ github.event.inputs.project_name }}/tables/external -type f -name "*.sql" | grep -q .; then
          for file in ./ADW/${VERSIONID}/${{ github.event.inputs.project_name }}/tables/external/*.sql; do
            sed -i "s/CREDENTIAL_NAME/$CREDENTIAL_NAME/g" "$file"
            sed -i "s/RAW_BUCKET/$RAW_BUCKET/g" "$file"
            sed -i "s/RAW_PRE_AUTH/$RAW_PRE_AUTH/g" "$file"
            sed -i "s/CURATED_BUCKET/$CURATED_BUCKET/g" "$file"
            sed -i "s/CURATED_PRE_AUTH/$CURATED_PRE_AUTH/g" "$file"
            sed -i "s/PRESENTATION_BUCKET/$PRESENTATION_BUCKET/g" "$file"
            sed -i "s/PRESENTATION_PRE_AUTH/$PRESENTATION_PRE_AUTH/g" "$file"
            sed -i "s/NAMESPACE/$NAMESPACE/g" "$file"
        done
        fi
        ./DevOps/plsql/main.sh
