name: Build Workflow

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
    outputs:
      release_version:
          description: 'Output from child workflow'
          value: ${{ jobs.run.outputs.release_version }}

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.step1.outputs.release_version }}
    steps:
      - name: Do something and set output
        id: step1
        run: |
          if [ "${{ github.event.inputs.release_version }}" = "" ]; then
            echo "Auto triggered"
            echo "release_version=v1.0.5" >> $GITHUB_OUTPUT
          else
            echo "Manually triggered"
            echo "release_version=${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT
          fi 

