name: CD-Deployment-Workflow

on:
  workflow_run:
    workflows: ["CI-Build-Workflow"]
    types:
      - completed

jobs:
  # Manual Approval Step before Deployment
  manual-approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Await manual approval from Farrukh
        uses: actions/github-script@v4
        with:
          script: |
            const { data: approvals } = await github.actions.listApprovals({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow_id,
              run_id: context.run_id,
            });

            const hasApproval = approvals.some(approval => approval.user.login === 'farrukh' && approval.state === 'APPROVED');
            if (!hasApproval) {
              core.setFailed("Approval from Farrukh is required before proceeding.");
            }
        timeout-minutes: 1440  # 24 hours (24*60 minutes)
        continue-on-error: true  # Allow failure if approval is not received

  # Deployment to STG/PRD based on approval
  deploy:
    needs: manual-approval
    if: ${{ needs.manual-approval.result == 'success' }}  # Only proceed if manual approval was successful
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # STG or PRD
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-package

      - name: Deploy to ${{ github.event.inputs.environment }} environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}..."
          # Add deployment commands here

      - name: Notify deployment complete
        run: echo "Deployment to ${{ github.event.inputs.environment }} complete!"

  # Cancel deployment if manual approval times out
  cancel-deployment:
    needs: manual-approval
    if: ${{ needs.manual-approval.result != 'success' }}  # If the manual approval failed or timed out
    runs-on: ubuntu-latest
    steps:
      - name: Cancel deployment
        run: echo "Manual approval not received within 24 hours. Cancelling deployment."
