name: CICD (Dev, Staging, Prod)

on:
  push:
    branches:
      - develop
  
  workflow_dispatch:
    inputs:
      release_version:
        type: choice
        description: Select the release version
        required: true
        options:
          - v1.0.0
          - v1.0.1
          - v1.0.2
          - v1.0.3
          - v1.0.4
          - v1.0.5    

jobs:
  
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_version: ${{ github.event.inputs.release_version }}

  test-approval-gate:
    needs: build
    environment: TEST
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: TEST
        run: echo "Approve for $(env.ENV_NAME)"
    
  test-deploy:
    needs: [build, test-approval-gate]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: TEST
      release_version: ${{ needs.build.outputs.release_version }}
    secrets: inherit

  staging-approval-gate:
    needs: test-deploy
    environment: STG
    runs-on: ubuntu-latest
    steps:
      - name: approved
        env: 
          ENV_NAME: STG
        run: echo "Approve for $(env.ENV_NAME)"
    
  staging-deploy:
    needs: [build, staging-approval-gate]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: STG
      release_version: ${{ needs.build.outputs.release_version }}
    secrets: inherit
