name: CICD (Dev, Test, Staging, Prod)

on:
  push:
    branches:
      - main
    paths:
      - 'ADW/**'
      - 'Test/**'

  workflow_dispatch:
    inputs:
      release_version:
        type: choice
        description: Select the release version
        required: true
        options:
          - v1.0.0
          - v1.0.1
          - v1.0.2
          - v1.0.3
          - v1.0.4
          - v1.0.5
      project_as_json:
        description: "JSON input of projects"
        required: true
        default: '{ "WATER_DM": "", "OPERATIONS_DM": "", "ENERGY_DM": "", "WQD_DM": "", "SOURCE_DM": "", "COMMON_DM": "" }'

jobs:

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "JSON_INPUT=${{ github.event.inputs.project_as_json }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=WATER_DM" >> $GITHUB_ENV  # Replace with desired project name
          echo "SELECTED_PROJECT=$(echo $JSON_INPUT | jq -r '.[$PROJECT_NAME]')" >> $GITHUB_ENV

    uses: ./.github/workflows/package.yml
    with:
      release_version: ${{ github.event.inputs.release_version }}
    secrets: inherit

  print-release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Version
        run: |
          echo "Selected release for deployment: ${{ needs.package.outputs.release_version }}"

  dev-deploy:
    needs: package
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: DEV
      release_version: ${{ needs.package.outputs.release_version }}
    secrets: inherit

  test-deploy:
    needs: [package, dev-deploy]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: TEST
      release_version: ${{ needs.package.outputs.release_version }}
    secrets: inherit
