name: "Deploy-Environment"

on:
  # This is a reusable workflow
  workflow_call:
    inputs: 
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string
      release_version:
        description: "Release version to deploy"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ${{ inputs.environment == 'TEST' && vars.RUNNER_NAME_TEST || (inputs.environment == 'STG' && vars.RUNNER_NAME_STG || vars.RUNNER_NAME_PROD) }}
    environment: ${{ inputs.environment }}

    steps:
    - name: Set up environment
      run: |
        echo "RELEASE_VERSION=${{ inputs.release_version }}" >> $GITHUB_ENV
        echo "Deploying release ${{ inputs.release_version }} to ${{ inputs.environment }}"

    - name: Ensure permissions
      run: chmod -R u+rwx ${{ github.workspace }}

    - name: Remove anything
      if: always()  # This ensures that the step runs regardless of the outcome of previous steps
      run: |
        rm -rf ${{ github.workspace }}/*
    
    - name: Download and extract release asset
      uses: robinraju/release-downloader@v1
      with:
        repository: ${{ github.repository }}
        tag: ${{ env.RELEASE_VERSION }}
        fileName: 'PBI-${{ env.RELEASE_VERSION }}.zip'
        latest: false
        extract: true

    - name: Remove line terminators
      run: |
        sed -i 's/\r//g' .github/config/workspace-deploy-config.yaml

    - name: Overwrite config file
      env: 
        WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
      run: | 
        var="${{ inputs.environment }}_WORKSPACE_ID"
        sed -i "s/$var/$WORKSPACE_ID/g" ".github/config/workspace-deploy-config.yaml"

    - name: Setup Workspace
      run: |
        if [ "${{ inputs.environment }}" == "DEV" ]; then
          workspace="Synergyze_Dev"
          echo "Deploying to workspace $workspace"
          echo "WORKSPACE=$workspace" >> $GITHUB_ENV
        elif [ "${{ inputs.environment }}" == "TEST" ]; then
          workspace="Synergyze_Test"
          echo "Deploying to workspace $workspace"
          echo "WORKSPACE=$workspace" >> $GITHUB_ENV
        fi

    - name: Deploy to Power BI workspace
      env:
        CONFIG_PATH: '.github/config/workspace-deploy-config.yaml'
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: | 
        python ./scripts/pbi.py