name: Detect Changed Schemas in PR

on:
  workflow_dispatch

jobs:
  detect-changed-schemas:
    runs-on: ubuntu-latest
    outputs:
      changed-schemas: ${{ steps.detect.outputs.changed_schemas }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Make script executable
        run: chmod +x .github/pyfiles/detect_changed_schema.py
  
      - name: Detect changed schemas
        id: detect
        run: .github/pyfiles/detect_changed_schema.py

  deploy:
    needs: detect-changed-schemas
    runs-on: ubuntu-latest
    steps:
      - name: Print changed schemas
        run: |
          echo "Schemas: ${{ needs.detect-changed-schemas.outputs.changed-schemas }}"
