name: Package Workflow

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
    outputs:
      release_version:
          description: 'Output from child workflow'
          value: ${{ jobs.prepare-release.outputs.release_version }}

jobs:

  create-package:
    if: ${{ inputs.release_version == '' }} 
    uses: ./.github/workflows/create-package.yml
    secrets: inherit

  prepare-release:
    needs: create-package
    if: always() && (needs.create-package.result == 'skipped' || needs.create-package.result == 'success')
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.step1.outputs.release_version }}
    steps:
      - name: Set release version
        id: step1
        run: |
          if [ "${{ inputs.release_version }}" != "" ]; then
            echo "Manually triggered"
            echo "release_version=${{ inputs.release_version }}" >> $GITHUB_OUTPUT
          else
            echo "Auto triggered"
            echo "release_version=${{ needs.create-package.outputs.release_version }}" >> $GITHUB_OUTPUT
          fi 

