name: SQL Lint Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'


jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install SQLFluff
        run: |
          pip install sqlfluff

      - name: Run SQL linter
        continue-on-error: true
        run: |
          sqlfluff parse sql/SYNERGYZE_AUDIT.sql --dialect ansi
          sqlfluff fix sql/SYNERGYZE_AUDIT.sql --dialect ansi
          sqlfluff lint sql/SYNERGYZE_AUDIT.sql --dialect ansi 
          
 
